### ISSUE TITLE
build script failing

### ISSUE THREAD

**Issue by jgroom33** [networkboot/docker-dhcpd#5] opened 2016-10-19 20:44 UTC
Possibly an issue with my docker (1.12.2) , but changing the COPY and the ENTRYPOINT resolved this error:

``` bash
ubuntu@ubuntu:~/ra_training/tester$ ./build
Sending build context to Docker daemon 153.6 kB
Step 1 : FROM ubuntu:xenial
 ---> f753707788c5
Step 2 : MAINTAINER Robin Smidsrød <robin@smidsrod.no>
 ---> Using cache
 ---> a84ade841be3
Step 3 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> e7e1708f98d2
Step 4 : RUN apt-get -q -y update  && apt-get -q -y -o "DPkg::Options::=--force-confold" -o "DPkg::Options::=--force-confdef" install apt-utils  && apt-get -q -y -o "DPkg::Options::=--force-confold" -o "DPkg::Options::=--force-confdef" dist-upgrade  && apt-get -q -y -o "DPkg::Options::=--force-confold" -o "DPkg::Options::=--force-confdef" install isc-dhcp-server man python3  && apt-get -q -y autoremove  && apt-get -q -y clean  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> ee660a5aaecc
Step 5 : COPY util/my_init.py /sbin/my_init
 ---> b49c9eab1310
Removing intermediate container cd9d90c708f0
Step 6 : COPY util/entrypoint.sh /entrypoint.sh
stat /var/lib/docker/aufs/mnt/fa23bc5aa628b9b22c64e63d941f8305b3523e5add5cb323a87049388c9c63f3/entrypoint.sh: no such file or directory
```

``` Dockerfile
FROM ubuntu:xenial

MAINTAINER Robin Smidsrød <robin@smidsrod.no>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -q -y update \
 && apt-get -q -y -o "DPkg::Options::=--force-confold" -o "DPkg::Options::=--force-confdef" install apt-utils \
 && apt-get -q -y -o "DPkg::Options::=--force-confold" -o "DPkg::Options::=--force-confdef" dist-upgrade \
 && apt-get -q -y -o "DPkg::Options::=--force-confold" -o "DPkg::Options::=--force-confdef" install isc-dhcp-server man python3 \
 && apt-get -q -y autoremove \
 && apt-get -q -y clean \
 && rm -rf /var/lib/apt/lists/*

COPY util/my_init.py /sbin/my_init
COPY util/entrypoint.sh /sbin/entrypoint.sh
# OLD: COPY util/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/sbin/entrypoint.sh"]
# OLD: ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by robinsmidsrod** [comment] 2016-10-20 09:15
Actually, this is a docker hub issue which is affecting the automated builds. The docker team is working on it, so I'm just going to let it be for now until they've come up with a proper fix. You can see one of their issues here: https://github.com/docker/hub-feedback/issues/811

**Comment by robinsmidsrod** [comment] 2016-12-20 17:37
If you've been bitten by this, upgrade to Docker engine 1.12.3, which should solve the issue. See the issue mentioned above for details on the root cause. Docker Hub has also been upgraded to a working verison of Docker Engine. Closing.

**Closed as completed** 2016-12-20 17:39 UTC
Labels: bug
